algoritmo "EXERCICIO 27"
var
   N1, N2: real
inicio

      Escreva("Digite um Valor: ")
      Leia(N1)
      Escreva("Digite outro Valor: ")
      Leia(N2)
      se N1 > N2 entao
         Escreva("O primeiro valor é o maior")
      fimse
      se N1 < N2 entao
         Escreva("O segundo valor é o maior")
      fimse
      se N1 = N2 entao
         Escreva("Não existe valor maior, os dois são iguais")
      fimse

fimalgoritmo