algoritmo "VIAJAR"
var
   din : inteiro
inicio

      Escreva("Quanto em dinheir vpocê tem para viajar? ")
      Leia(din)
      se (din >= 10000) entao
         Escreva("Partiu Disney!!!")
      senao
           se (din >= 5000) e (din < 10000) entao
              Escreva("Visitar a Familia!")
           senao
              Escreva("Tô liso, vou ficar em Casa.")
           fimSe
      fimSe
fimalgoritmo